"""Auto-fit slides : detecte l'overflow et reduit automatiquement le font-size par slide.

Usage:
    python auto_fit_slides.py path/to/deck.html

Pour chaque slide qui overflow (contenu > 720px hauteur), ce script :
1. Mesure le depassement via Playwright headless
2. Cherche par dichotomie le plus grand font-size entre 18 et 26px qui fait rentrer
3. Injecte un `<style>` dans le HTML avec un override `section:nth-of-type(N) { font-size: Xpx }`

Le HTML est modifie in-place. Le reste du styling (padding, gap, etc.) s'ajuste en em.

Best-effort : si aucun font-size dans la plage ne fait rentrer, on laisse 18px (minimum)
et on log un warning pour revue manuelle.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


VIEWPORT_WIDTH = 1280
VIEWPORT_HEIGHT = 720
MIN_FONT_PX = 18
MAX_FONT_PX = 26  # taille de reference du theme
TOLERANCE_PX = 4


def measure_overflow(page, section_index: int) -> int:
    """Retourne la difference scrollHeight - clientHeight (0 = no overflow)."""
    return page.evaluate(
        """(idx) => {
            const s = document.querySelectorAll('section')[idx];
            if (!s) return 0;
            return Math.max(0, s.scrollHeight - s.clientHeight);
        }""",
        section_index,
    )


def set_section_font(page, section_index: int, font_px: int):
    """Applique un font-size temporaire a la section via JS pour mesurer."""
    page.evaluate(
        """(args) => {
            const s = document.querySelectorAll('section')[args.idx];
            if (s) s.style.fontSize = args.font + 'px';
        }""",
        {"idx": section_index, "font": font_px},
    )


def find_best_font(page, section_index: int) -> int | None:
    """Dichotomie : retourne le plus grand font-size qui fait rentrer la slide, ou None."""
    lo, hi = MIN_FONT_PX, MAX_FONT_PX
    best_fit = None
    while lo <= hi:
        mid = (lo + hi) // 2
        set_section_font(page, section_index, mid)
        page.wait_for_timeout(100)
        overflow = measure_overflow(page, section_index)
        if overflow <= TOLERANCE_PX:
            best_fit = mid
            lo = mid + 1  # essaie plus grand
        else:
            hi = mid - 1
    # Reset
    set_section_font(page, section_index, MAX_FONT_PX)
    return best_fit


def main():
    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <path-to-marp.html>")
        sys.exit(1)

    html_path = Path(sys.argv[1])
    if not html_path.exists():
        print(f"File not found: {html_path}")
        sys.exit(1)

    from playwright.sync_api import sync_playwright

    overrides: dict[int, int] = {}  # section_index (0-based) -> font_px

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        ctx = browser.new_context(viewport={"width": VIEWPORT_WIDTH, "height": VIEWPORT_HEIGHT})
        page = ctx.new_page()
        page.goto(f"file:///{html_path.resolve().as_posix()}")
        page.wait_for_timeout(1500)  # let Marp bespoke JS render

        count = page.evaluate("() => document.querySelectorAll('section').length")
        print(f"\nAuto-fit {html_path.name} : {count} slides")

        for i in range(count):
            overflow = measure_overflow(page, i)
            if overflow <= TOLERANCE_PX:
                continue
            title = page.evaluate(
                """(idx) => {
                    const s = document.querySelectorAll('section')[idx];
                    const h = s?.querySelector('h1, h2, h3');
                    return h ? h.textContent.trim().slice(0, 50) : '(no title)';
                }""",
                i,
            )
            best = find_best_font(page, i)
            if best is None or best < MAX_FONT_PX:
                size = best if best is not None else MIN_FONT_PX
                overrides[i] = size
                status = "fit" if best else f"truncated at {MIN_FONT_PX}px"
                print(f"  Slide {i + 1:2d} [+{overflow:3d}px]: {size}px ({status}) — {title}")

        browser.close()

    if not overrides:
        print("ALL FIT — no auto-adjustment needed.\n")
        return

    # Injecter les overrides CSS dans le HTML
    css_rules = "\n".join(
        f"  div#\\:\\$p > svg > foreignObject > section:nth-of-type({i + 1}), "
        f"body > section:nth-of-type({i + 1}) "
        f"{{ font-size: {font}px !important; }}"
        for i, font in sorted(overrides.items())
    )
    style_block = f"""
<style id="auto-fit-overrides">
/* Auto-generated by auto_fit_slides.py — per-slide font-size reductions for overflow */
{css_rules}
</style>
"""
    content = html_path.read_text(encoding="utf-8")
    # Remove previous auto-fit block if present
    content = re.sub(
        r'<style id="auto-fit-overrides">.*?</style>',
        "",
        content,
        flags=re.DOTALL,
    )
    if "</body>" in content:
        content = content.replace("</body>", style_block + "</body>")
    else:
        content += style_block
    html_path.write_text(content, encoding="utf-8")
    print(f"\n{len(overrides)} override(s) injected into {html_path.name}\n")


if __name__ == "__main__":
    main()
